### PR TITLE
Add C extension flag to GN (conflicts)

### PR DESCRIPTION
**Pull request by taoliq**
Add C extension flag in GN.

Since this patch should corpate collaborate with build/config/riscv.gni, which is still [on reviewing](https://chromium-review.googlesource.com/c/chromium/src/+/2793961).

Please create build/config/riscv.gni manually (copy the file from the link above).

### CODE REVIEW

**Review by qjivy — APPROVED** [review]

**Comment by lazyparser** [comment]
seems there is a build failure.

```
#18 1.695 ERROR at //BUILD.gn:10:1: Unable to load "/v8/build/config/riscv.gni".
#18 1.695 import("//build/config/riscv.gni")
```

**Comment by taoliq** [comment]
> 
> 
> seems there is a build failure.
> 
> ```
> #18 1.695 ERROR at //BUILD.gn:10:1: Unable to load "/v8/build/config/riscv.gni".
> #18 1.695 import("//build/config/riscv.gni")
> ```

The build failure is reasonable. Because the dependency is still reviewing in the upstream. Here it is.

https://chromium-review.googlesource.com/c/chromium/src/+/2793961

**Review by lazyparser — COMMENTED** [review]
/retest

**Pull request closed without merging**
