### PR TITLE
Fix Issue #403..

### LINKED ISSUE #403: wasm-spec-tests/proposals/js-types/exports and imports fail
**Describe the bug**
Two tests fail with the latest rebased branch:
* wasm-spec-tests/proposals/js-types/exports
* wasm-spec-tests/proposals/js-types/imports

**To Reproduce**
1. Checkout 'rebase-to-master':
  ```
  git checkout rebase-to-master
  ```
2. Build:
  ```
  ./tools/dev/gm.py riscv64.debug.all
  ```
3. Run tests:
   ```
   out/riscv64.debug/d8 --test test/wasm-spec-tests/tests/proposals/js-types/exports.js --random-seed=-157172359 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-type-reflection --wasm-staging

   out/riscv64.debug/d8 --test test/wasm-spec-tests/tests/proposals/js-types/imports.js --random-seed=-157172359 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-type-reflection --wasm-staging
   ```

**Expected behavior**
These tests should pass.

**Errors/Logs**
```
#15 5293. === wasm-spec-tests/proposals/js-types/exports ===
#15 5293. Command: /v8/out/riscv64.debug/d8 --test /v8/test/wasm-spec-tests/tests/proposals/js-types/exports.js --random-seed=-157172359 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-type-reflection --wasm-staging
#15 5293. === wasm-spec-tests/proposals/js-types/imports ===
#15 5293. --- stdout ---
#15 5293. 13
#15 5293. 14 42
#15 5293. 13
#15 5293. 13
#15 5293. 13
#15 5293. 13
#15 5293. 25 53
#15 5293. 24
#15 5293. 24
#15 5293. 24
#15 5293. /v8/test/wasm-spec-tests/tests/proposals/js-types/imports.js:78: Error: Wasm validation failure expected
#15 5293.   throw new Error("Wasm validation failure expected");
#15 5293.   ^
#15 5293. Error: Wasm validation failure expected
#15 5293.     at assert_invalid (/v8/test/wasm-spec-tests/tests/proposals/js-types/imports.js:78:9)
#15 5293.     at /v8/test/wasm-spec-tests/tests/proposals/js-types/imports.js:336:1
#15 5293. Command: /v8/out/riscv64.debug/d8 --test /v8/test/wasm-spec-tests/tests/proposals/js-types/imports.js --random-seed=-157172359 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-type-reflection --wasm-staging
#15 5293. 
#15 5293. ===
#15 5293. === 2 tests failed
#15 5293. ===
```

### PR DESCRIPTION
**Pull request by luyahan**
Fix #403

### CODE REVIEW

**Comment by luyahan** [comment]
'proposals/js-types/exports':
don't failed now.

**Review by qjivy — APPROVED** [review]

**Review by lazyparser — APPROVED** [review]

**Pull request closed without merging**
